# ***************************** CONFIGURATION ******************************** #

NAME			:=	FragTrap
MSG_PROGRESS	:=	"🤖"
MSG_USAGE		?=	"\nUsage: ./$(NAME)\n"
COLOR_MAKE		:=	STY_GRE

include				../global.mk
