# ***************************** CONFIGURATION ******************************** #

NAME			:=	FragTrap
MSG_PROGRESS	:=	"🤖"
MSG_USAGE		?=	"Usage: ./$(NAME)"
COLOR_MAKE		:=	STY_GRE

include				$(shell git rev-parse --show-toplevel)/global.mk
