# ***************************** CONFIGURATION ******************************** #

NAME			:=	ScavTrap
MSG_PROGRESS	:=	"🤖"
MSG_USAGE		?=	"\nUsage: ./$(NAME)\n"
COLOR_MAKE		:=	STY_RED

include				$(shell git rev-parse --show-toplevel)/global.mk
