# ***************************** CONFIGURATION ******************************** #

NAME			:=	horde
MSG_PROGRESS	:=	"🧟"
MSG_USAGE		?=	"Usage: ./$(NAME) [number] [name]"
COLOR_MAKE		:=	STY_GRE

include				$(shell git rev-parse --show-toplevel)/global.mk
