# ***************************** CONFIGURATION ******************************** #

NAME			:=	horde
MSG_PROGRESS	:=	"🧟"
MSG_USAGE		?=	"\nUsage: ./$(NAME) [number] [name]\n"
COLOR_MAKE		:=	STY_GRE

include				../global.mk
