include				$(shell git rev-parse --show-toplevel)/Makefiles/setup.mk


# ***************************** CONFIGURATION ******************************** #

NAME			:=	horde
MSG_PROGRESS	:=	"🧟"
MSG_USAGE		?=	"Usage: ./$(NAME) [number] [name]"
COLOR_MAKE		:=	STY_GRE


include				$(MAKEFILES_DIR)/config.mk
include				$(MAKEFILES_DIR)/build.mk
