# ***************************** CONFIGURATION ******************************** #

NAME			:=	DiamondTrap
MSG_PROGRESS	:=	"🤖"
MSG_USAGE		?=	"Usage: ./$(NAME)\n"
COLOR_MAKE		:=	STY_CYA

include				$(shell git rev-parse --show-toplevel)/global.mk
