include				$(shell git rev-parse --show-toplevel)/Makefiles/setup.mk


# ***************************** CONFIGURATION ******************************** #

NAME			:=	DiamondTrap
MSG_PROGRESS	:=	"🤖"
MSG_USAGE		?=	"Usage: ./$(NAME)"
COLOR_MAKE		:=	STY_CYA


include				$(MAKEFILES_DIR)/global.mk
