# ***************************** CONFIGURATION ******************************** #

NAME			:=	weapon
MSG_PROGRESS	:=	"🪓"
MSG_USAGE		?=	"\nUsage: ./$(NAME)\n"
COLOR_MAKE		:=	STY_RED

include				../global.mk
