include				$(shell git rev-parse --show-toplevel)/Makefiles/setup.mk


# ***************************** CONFIGURATION ******************************** #

NAME			:=	weapon
MSG_PROGRESS	:=	"🪓"
MSG_USAGE		?=	"Usage: ./$(NAME)"
COLOR_MAKE		:=	STY_RED


include				$(MAKEFILES_DIR)/global.mk
