# ***************************** CONFIGURATION ******************************** #

NAME			:=	28B
MSG_PROGRESS	:=	"📋"
MSG_USAGE		?=	"\nUsage: ./$(NAME)\n"
COLOR_MAKE		:=	STY_YEL

include				../global.mk
