# ***************************** CONFIGURATION ******************************** #

NAME			:=	megaphone
MSG_PROGRESS	:=	"📢"
MSG_USAGE		?=	"Usage: ./$(NAME) \"[message]\" \"[...]\""
COLOR_MAKE		:=	STY_WHI

include				$(shell git rev-parse --show-toplevel)/global.mk
