include				$(shell git rev-parse --show-toplevel)/Makefiles/setup.mk


# ***************************** CONFIGURATION ******************************** #

NAME			:=	megaphone
MSG_PROGRESS	:=	"📢"
MSG_USAGE		?=	"Usage: ./$(NAME) \"[message]\" \"[...]\""
COLOR_MAKE		:=	STY_WHI


include				$(MAKEFILES_DIR)/global.mk
