# ***************************** CONFIGURATION ******************************** #

NAME			:=	megaphone
MSG_PROGRESS	:=	"📢"
MSG_USAGE		?=	"\nUsage: ./$(NAME) \"[message]\" \"[...]\"\n"
COLOR_MAKE		:=	STY_WHI

include				../global.mk
