# ***************************** CONFIGURATION ******************************** #

NAME			:=	harl
MSG_PROGRESS	:=	"😡"
MSG_USAGE		?=	"Usage: ./$(NAME) [complaint_level] [...]"
COLOR_MAKE		:=	STY_YEL

include				$(shell git rev-parse --show-toplevel)/Makefiles/global.mk
