# ***************************** CONFIGURATION ******************************** #

NAME			:=	sed
MSG_PROGRESS	:=	"📄"
MSG_USAGE		?=	"Usage: ./$(NAME) <filename> <search> <replace>"
COLOR_MAKE		:=	STY_WHI

include				$(shell git rev-parse --show-toplevel)/global.mk
