include				$(shell git rev-parse --show-toplevel)/Makefiles/setup.mk


# ***************************** CONFIGURATION ******************************** #

NAME			:=	sed
MSG_PROGRESS	:=	"📄"
MSG_USAGE		?=	"Usage: ./$(NAME) <filename> <search> <replace>"
COLOR_MAKE		:=	STY_WHI


include				$(MAKEFILES_DIR)/config.mk
include				$(MAKEFILES_DIR)/build.mk
