# ***************************** CONFIGURATION ******************************** #

NAME			:=	sed
MSG_PROGRESS	:=	"📄"
MSG_USAGE		?=	"\nUsage: ./$(NAME) <filename> <search> <replace>\n"
COLOR_MAKE		:=	STY_WHI

include				../global.mk
