# ***************************** CONFIGURATION ******************************** #

NAME			:=	bureaucrat
MSG_PROGRESS	:=	"💼"
MSG_USAGE		?=	"Usage: ./$(NAME)"
COLOR_MAKE		:=	STY_YEL

include				$(shell git rev-parse --show-toplevel)/Makefiles/global.mk
