# ***************************** CONFIGURATION ******************************** #

NAME			:=	bureaucrat
MSG_PROGRESS	:=	"💼"
MSG_USAGE		?=	"\nUsage: ./$(NAME)\n"
COLOR_MAKE		:=	STY_YEL

include				$(shell git rev-parse --show-toplevel)/global.mk
