include				$(shell git rev-parse --show-toplevel)/Makefiles/setup.mk


# ***************************** CONFIGURATION ******************************** #

NAME			:=	Span
MSG_PROGRESS	:=	"🌉"
MSG_USAGE		?=	"Usage: ./$(NAME) [nbr] [...]"
COLOR_MAKE		=	$(STY_RED)
LIBS_LOCAL		=	$(LIB_ROOT_DIR)/libftpp/libftpp.a


include				$(MAKEFILES_DIR)/config.mk
include				$(MAKEFILES_DIR)/build.mk
include				$(MAKEFILES_DIR)/doc.mk
include				$(MAKEFILES_DIR)/help.mk
