# ***************************** CONFIGURATION ******************************** #

NAME			:=	libutils.a
MSG_PROGRESS	:=	"📦"
# MSG_USAGE		?=	"\nUsage: ./$(NAME)\n"
COLOR_MAKE		:=	STY_WHI

include				$(shell git rev-parse --show-toplevel)/global.mk
