include				$(shell git rev-parse --show-toplevel)/Makefiles/setup.mk


# ***************************** CONFIGURATION ******************************** #

NAME			:=	easyfind
MSG_PROGRESS	:=	"🔎"
MSG_USAGE		?=	"Usage: ./$(NAME) [container_size]"
COLOR_MAKE		=	$(STY_BLU)
LIBRARIES		=	$(LIB_ROOT_DIR)/libftpp/libftpp.a


include				$(MAKEFILES_DIR)/config.mk
include				$(MAKEFILES_DIR)/build.mk
include				$(MAKEFILES_DIR)/doc.mk
include				$(MAKEFILES_DIR)/help.mk
