include				$(shell git rev-parse --show-toplevel)/Makefiles/setup.mk


# ***************************** CONFIGURATION ******************************** #

NAME			:=	materia
MSG_PROGRESS	:=	"🔮"
MSG_USAGE		?=	"Usage: ./$(NAME)"
COLOR_MAKE		:=	STY_MAG


include				$(MAKEFILES_DIR)/global.mk
