# ***************************** CONFIGURATION ******************************** #

NAME			:=	materia
MSG_PROGRESS	:=	"🐾"
MSG_USAGE		?=	"\nUsage: ./$(NAME)\n"
COLOR_MAKE		:=	STY_MAG

include				../global.mk
