# ***************************** CONFIGURATION ******************************** #

NAME			:=	bsp
MSG_PROGRESS	:=	"📐"
MSG_USAGE		?=	"\nUsage: ./$(NAME) <x> <y> (in unit triangle: 📐)\n"
COLOR_MAKE		:=	STY_YEL

include				../global.mk
