include				$(shell git rev-parse --show-toplevel)/Makefiles/setup.mk


# ***************************** CONFIGURATION ******************************** #

NAME			:=	account
MSG_PROGRESS	:=	"👤"
MSG_USAGE		?=	"Usage: ./$(NAME) [> logfile]"
COLOR_MAKE		:=	STY_BLU


include				$(MAKEFILES_DIR)/global.mk
