# ***************************** CONFIGURATION ******************************** #

NAME			:=	account
MSG_PROGRESS	:=	"👤"
MSG_USAGE		?=	"Usage: ./$(NAME) [> logfile]\n"
COLOR_MAKE		:=	STY_BLU

include				$(shell git rev-parse --show-toplevel)/global.mk
