# ***************************** CONFIGURATION ******************************** #

NAME			:=	account
MSG_PROGRESS	:=	"👤"
MSG_USAGE		?=	"\nUsage: ./$(NAME) [> logfile]\n"
COLOR_MAKE		:=	STY_BLU

include				../global.mk
