include				$(shell git rev-parse --show-toplevel)/Makefiles/setup.mk


# ***************************** CONFIGURATION ******************************** #

NAME			:=	harlFilter
MSG_PROGRESS	:=	"🤬"
MSG_USAGE		?=	"Usage: ./$(NAME) [complaint_level] [...]"
COLOR_MAKE		:=	STY_YEL


include				$(MAKEFILES_DIR)/global.mk
