# ***************************** CONFIGURATION ******************************** #

NAME			:=	harlFilter
MSG_PROGRESS	:=	"🤬"
MSG_USAGE		?=	"Usage: ./$(NAME) [complaint_level] [...]\n"
COLOR_MAKE		:=	STY_YEL

include				$(shell git rev-parse --show-toplevel)/global.mk
