include				$(shell git rev-parse --show-toplevel)/Makefiles/setup.mk


# ***************************** CONFIGURATION ******************************** #

NAME			:=	intern
MSG_PROGRESS	:=	"🎓"
MSG_USAGE		?=	"Usage: ./$(NAME)"
COLOR_MAKE		:=	STY_YEL


include				$(MAKEFILES_DIR)/global.mk
