# ***************************** CONFIGURATION ******************************** #

NAME			:=	animal
MSG_PROGRESS	:=	"🐾"
MSG_USAGE		?=	"\nUsage: ./$(NAME)\n"
COLOR_MAKE		:=	STY_BLU

include				../global.mk
