# ***************************** CONFIGURATION ******************************** #

NAME			:=	brain
MSG_PROGRESS	:=	"🧠"
MSG_USAGE		?=	"Usage: ./$(NAME)\n"
COLOR_MAKE		:=	STY_RED

include				$(shell git rev-parse --show-toplevel)/global.mk
