include				$(shell git rev-parse --show-toplevel)/Makefiles/setup.mk


# ***************************** CONFIGURATION ******************************** #

NAME			:=	zombie
MSG_PROGRESS	:=	"🧟"
MSG_USAGE		?=	"Usage: ./$(NAME)"
COLOR_MAKE		:=	STY_GRE


include				$(MAKEFILES_DIR)/global.mk
