# ***************************** CONFIGURATION ******************************** #

NAME			:=	zombie
MSG_PROGRESS	:=	"🧟"
MSG_USAGE		?=	"\nUsage: ./$(NAME)\n"
COLOR_MAKE		:=	STY_GRE

include				../global.mk
