include				$(shell git rev-parse --show-toplevel)/Makefiles/setup.mk


# ***************************** CONFIGURATION ******************************** #

NAME			:=	animal
MSG_PROGRESS	:=	"🧠"
MSG_USAGE		?=	"Usage: ./$(NAME) [animal_count (default: 10)]"
COLOR_MAKE		:=	STY_RED


include				$(MAKEFILES_DIR)/config.mk
include				$(MAKEFILES_DIR)/build.mk
