# ***************************** CONFIGURATION ******************************** #

NAME			:=	animal
MSG_PROGRESS	:=	"🧠"
MSG_USAGE		?=	"Usage: ./$(NAME) [animal_count (default: 10)]\n"
COLOR_MAKE		:=	STY_RED

include				$(shell git rev-parse --show-toplevel)/global.mk
