# ***************************** CONFIGURATION ******************************** #

NAME			:=	animal
MSG_PROGRESS	:=	"💭"
MSG_USAGE		?=	"\nUsage: ./$(NAME) [animal_count (default: 10)]\n"
COLOR_MAKE		:=	STY_WHI

include				$(shell git rev-parse --show-toplevel)/global.mk
