# ***************************** CONFIGURATION ******************************** #

NAME			:=	animal
MSG_PROGRESS	:=	"💭"
MSG_USAGE		?=	"\nUsage: ./$(NAME)\n"
COLOR_MAKE		:=	STY_WHI

include				../global.mk
